-- CreateTable
CREATE TABLE `VolunteerApplication` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `fullName` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `phone` VARCHAR(191) NOT NULL,
    `dob` DATETIME(3) NULL,
    `gender` VARCHAR(191) NULL,
    `nationality` VARCHAR(191) NULL,
    `occupation` VARCHAR(191) NULL,
    `address` VARCHAR(191) NULL,
    `emergencyName` VARCHAR(191) NULL,
    `emergencyPhone` VARCHAR(191) NULL,
    `position` VARCHAR(191) NULL,
    `department` JSON NOT NULL,
    `duration` VARCHAR(191) NULL,
    `arrangement` VARCHAR(191) NULL,
    `startDate` DATETIME(3) NULL,
    `supervisor` VARCHAR(191) NULL,
    `agreements` JSON NOT NULL,
    `mediaConsent` BOOLEAN NOT NULL DEFAULT false,
    `volunteerName` VARCHAR(191) NULL,
    `signature` VARCHAR(191) NULL,
    `declarationDate` DATETIME(3) NULL,
    `status` VARCHAR(191) NOT NULL DEFAULT 'Pending',
    `approvedBy` VARCHAR(191) NULL,
    `approverPosition` VARCHAR(191) NULL,
    `approverSignature` VARCHAR(191) NULL,
    `approvalDate` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
